# Generated by Django 5.2.3 on 2025-06-28 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapi', '0002_product_remove_session_identifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=30, null=True)),
                ('hash_url', models.CharField(blank=True, max_length=30, null=True)),
                ('continue_uri', models.CharField(max_length=30)),
                ('continue_access', models.CharField(max_length=30)),
                ('quote_id', models.CharField(max_length=30)),
                ('incomming_payment_id', models.CharField(max_length=30)),
                ('session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paymentapi.session')),
            ],
        ),
    ]
