# Generated by Django 5.2.3 on 2025-06-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapi', '0003_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='debit_amount',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
