# Generated by Django 5.2.3 on 2025-06-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapi', '0004_grant_debit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='manage_url',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
